-- Insert common medical specializations in Indonesia
INSERT INTO specialization (name, description, created_at, updated_at) VALUES
('Dokter Umum', 'Praktisi medis umum yang menangani berbagai kondisi kesehatan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Anak', 'Spesialis yang fokus pada kesehatan anak-anak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Penyakit Dalam', 'Spesialis yang menangani penyakit internal pada orang dewasa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Bedah', 'Spesialis yang melakukan prosedur pembedahan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Kandungan dan Kebidanan', 'Spesialis yang menangani kesehatan reproduksi wanita dan kehamilan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Jantung', 'Spesialis yang menangani penyakit jantung dan pembuluh darah', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Saraf', 'Spesialis yang menangani gangguan sistem saraf', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Mata', 'Spesialis yang menangani kesehatan mata dan gangguan penglihatan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter THT', 'Spesialis telinga, hidung, dan tenggorokan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Kulit dan Kelamin', 'Spesialis yang menangani penyakit kulit dan kelamin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Gigi', 'Spesialis yang menangani kesehatan gigi dan mulut', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Jiwa', 'Spesialis yang menangani kesehatan mental', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Paru', 'Spesialis yang menangani penyakit paru-paru dan pernapasan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Ortopedi', 'Spesialis yang menangani gangguan tulang, sendi, dan otot', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Urologi', 'Spesialis yang menangani sistem kemih dan reproduksi pria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Radiologi', 'Spesialis yang menginterpretasikan hasil pencitraan medis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Anestesi', 'Spesialis yang memberikan anestesi dan manajemen nyeri', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Gizi Klinik', 'Spesialis yang menangani nutrisi dan diet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Forensik', 'Spesialis yang menangani aspek medis dalam penyelidikan hukum', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Rehabilitasi Medik', 'Spesialis yang membantu pemulihan pasien pasca cedera atau penyakit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);